# Generated by Django 3.0.5 on 2020-12-21 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreetingApp', '0002_auto_20201220_0346'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='GreetingCard',
        ),
    ]
